# Generated by Django 3.2.5 on 2021-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=6)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=7)),
                ('age', models.CharField(max_length=4)),
                ('married', models.CharField(choices=[('No', 'NO'), ('Yes', 'YES')], max_length=4)),
                ('graduated', models.CharField(choices=[('No', 'NO'), ('Yes', 'YES')], max_length=4)),
                ('profession', models.CharField(choices=[('Healthcare', 'Healthcare'), ('Engineer', 'Engineer'), ('Lawyer', 'Lawyer'), ('Doctor', 'Doctor'), ('Entertainment', 'Entertainment'), ('Artist', 'Artist'), ('Executive', 'Executive'), ('Homemaker', 'Homemaker'), ('Marketing', 'Marketing')], max_length=15)),
                ('work_expression', models.CharField(max_length=3)),
                ('spending', models.CharField(choices=[('Low', 'LOW'), ('Average', 'AVERAGE'), ('High', 'HIGH')], max_length=8)),
                ('family_size', models.CharField(max_length=3)),
                ('segment', models.CharField(blank=True, default='None', max_length=4)),
            ],
        ),
    ]
