# Generated by Django 3.2.5 on 2021-10-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='work_expression',
            new_name='work_experience',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='category',
            field=models.CharField(choices=[('Var_1_0', '1'), ('Var_1_1', '2'), ('Var_1_2', '3'), ('Var_1_3', '4'), ('Var_1_4', '5'), ('Var_1_5', '6'), ('Var_1_6', '7'), ('Var_1_7', '8'), ('Var_1_8', '8')], default='None', max_length=8),
        ),
    ]
